set quiet
bangbash := '#!/usr/bin/env bash'

# nix flake check
check:
        nix flake check --no-build --all-systems --verbose
# checking nix lang syntax before build or install
check-syntax $path:
        nix-instantiate --parse-only {{path}}

# list available machine 
machine:
        grep -Po '^\s*\K[\w-]+(?=\s*=)' flake.nix | tail -n 8 | head -n 4 | paste -sd " " | \
                awk '{print "\033[0;34mMachine:\033[0;32m\n\t"$1"\n\t"$2"\n\t"$3"\n\t"$4}'

# pkgs nix-env -iA nixos.<pkgs> (git, just, fish, neovim)
tools:
        nix-env -iA nixos.git nixos.neovim nixos.fish nixos.just

# clean nix-collect-garbage -d
clean:
        nix-collect-garbage -d

# nix store optimise --verbose
clean-store:
        nix store optimise --verbose

# clean nix-collect-garbage older than x days
clean-old $day:
        nix-collect-garbage --delete-older-than {{day}}d

# show available configurations
show:
        nix flake show  --experimental-features 'nix-command flakes'

# generate nixos config on this machine
gen:
        nixos-generate-config --root /mnt

# install nixos with flake 
install $machine *arg:
        # remote luks unlocking
        @if [[ ! -d "/mnt/etc/secrets/initrd" && (("{{machine}}" = "vm" || "{{machine}}" = "vm-btrfs") || "{{machine}}" = "vm-zfs") ]]; then \
                sudo mkdir -p /mnt/etc/secrets/initrd; \
                sudo ssh-keygen -t ed25519 -N "" -f /mnt/etc/secrets/initrd/ssh_host_ed25519_key; \
        fi
        @echo run nixos-install...
        sudo nixos-install --flake .#{{machine}} {{arg}}
# install nixos with flake from cache.nummtide.com
install-through-cache $machine *arg:
        # remote luks unlocking
        @if [[ ! -d "/mnt/etc/secrets/initrd" && (("{{machine}}" = "vm" || "{{machine}}" = "vm-btrfs") || "{{machine}}" = "vm-zfs") ]]; then \
                sudo mkdir -p /mnt/etc/secrets/initrd; \
                sudo ssh-keygen -t ed25519 -N "" -f /mnt/etc/secrets/initrd/ssh_host_ed25519_key; \
        fi
        @echo run nixos-install...
        sudo nixos-install \
                --option extra-substituters "https://cache.numtide.com" \
                --option extra-trusted-public-keys "niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=" \
                --flake .#{{machine}} {{arg}}
        
# build list
build-list:
        nixos-rebuild list-generations

# build test
build-test $machine *arg:
        nixos-rebuild test --flake .#{{machine}} --ask-sudo-password {{arg}}

# rebuild nixos with flake apply now live add -L to print all jobs
build $machine *arg:
        nixos-rebuild switch --flake .#{{machine}} --ask-sudo-password {{arg}}

# rebuild nixos with flake apply on next boot add -L to print all jobs
build-later $machine *arg:
        nixos-rebuild boot --flake .#{{machine}} --ask-sudo-password {{arg}}

# nix-store query packages
query $query:
        nix-store --query --requisites /run/current-system | grep -i {{query}}

# vm full setup
flake-vm-gui:
        just flake-full vm
        just flake-compositor vm
        just flake-display-sddm vm
        just build-later vm -L
# notebook full setup
flake-notebook-gui:
        just flake-full notebook
        just flake-compositor notebook
        just flake-display-sddm notebook
        just build-later notebook -L
# pc full setup
flake-pc-gui:
        just flake-full pc
        just flake-compositor pc
        just flake-display-sddm pc
        just build-later pc -L

# flake update
flake-up:
        nix flake update

# change user for x machine flake.nix
flake-user $machine $user:
        @if [[ "{{machine}}" == "vm" ]]; then \
                sed -i '/users = \[/s/"[^"]*"/"{{user}}"/' flake.nix; \
        elif [[ "{{machine}}" == "notebook" ]]; then \
                sed -i '/users = \[/s/"[^"]*"/"{{user}}"/2' flake.nix; \
        else \
                sed -i '/users = \[/s/"[^"]*"/"{{user}}"/3' flake.nix; \
        fi
        rg -Po '(?<=users = \[ ).*?(?= \])' flake.nix | \
                paste -sd "" | \
                awk '{print "\033[0;34mvm:\033[0;32m "$1"\n""\033[0;34mnotebook:\033[0;32m "$2"\n""\033[0;34mpc:\033[0;32m "$3}'
# change host for x machine flake.nix
flake-host $machine $host:
        @if [[ "{{machine}}" == "vm" ]]; then \
                sed -i '/hostname = \[/s/"[^"]*"/"{{host}}"/' flake.nix; \
        elif [[ "{{machine}}" == "notebook" ]]; then \
                sed -i '/hostname = \[/s/"[^"]*"/"{{host}}"/2' flake.nix; \
        else \
                sed -i '/hostname = \[/s/"[^"]*"/"{{host}}"/3' flake.nix; \
        fi
        rg -Po '(?<=hostname = \[ ).*?(?= \])' flake.nix | \
                paste -sd "" | \
                awk '{print "\033[0;34mvm:\033[0;32m "$1"\n""\033[0;34mnotebook:\033[0;32m "$2"\n""\033[0;34mpc:\033[0;32m "$3}'
# change machine base = minimal, full = with gui
flake-full $machine:
        {{bangbash}}
        sed -i 's/base/full/' users/{{machine}}/default.nix
        sed -i 's/base/full/' homemanager/{{machine}}/default.nix
        printf "\033[0;34mflake-full:\n"
        rg -i "full" users/{{machine}}/default.nix | head -n 1 | \
                paste -sd "" |  awk '{print "\033[0;32m" $0}'
        rg -i "full" homemanager/{{machine}}/default.nix | head -n 1 | \
                paste -sd "" |  awk '{print "\033[0;32m" $0}'
# change machine base = minimal, full = with gui
flake-base $machine:
        {{bangbash}}
        sed -i 's/full/base/' users/{{machine}}/default.nix
        sed -i 's/full/base/' homemanager/{{machine}}/default.nix
        printf "\033[0;34mflake-base:\n"
        rg -i "base" users/{{machine}}/default.nix | head -n 1 | \
                paste -sd "" | awk '{print "\033[0;32m" $0}'
        rg -i "base" homemanager/{{machine}}/default.nix | head -n 1 | \
                paste -sd "" | awk '{print "\033[0;32m" $0}'
# mv compositor to mangowm
flake-mango $machine:
        {{bangbash}}
        sed -i 's/# inputs.mangowm.nixosModules.mango/inputs.mangowm.nixosModules.mango/' users/{{machine}}/full.nix
        # sed -i 's/exec start-hyprland/# exec start-hyprland/' modules/{{machine}}/full.nix
        # sed -i 's/# exec mango/exec mango/' modules/{{machine}}/full.nix
        sed -i 's/# mango.enable = true;/mango.enable = true;/' users/{{machine}}/full.nix
        sed -i 's/# ..\/..\/modules/mangowm.nix/..\/..\/modules/mangowm.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/..\/..\/modules/hyprland.nix/# ..\/..\/modules/hyprland.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/..\/..\/modules/hyprpaper.nix/# ..\/..\/modules/hyprpaper.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/xdg-desktop-portal-hyprland/# xdg-desktop-portal-hyprland/' homemanager/{{machine}}/full.nix
        rg -i "inputs.mangowm.nixosModules.mango" users/{{machine}}/full.nix | awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -i "xdg-desktop-portal-hyprland" homemanager/{{machine}}/full.nix | \
                awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -i "mango.enable = true;" homemanager/{{machine}}/full.nix | \
                awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -U -o 'imports\s*=\s*\[(\p{any}*?)\]' -r '$1' --no-line-number homemanager/{{machine}}/full.nix | \
                awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
# default comopositor hyprland
flake-hypr $machine:
        {{bangbash}}
        sed -i 's/inputs.mangowm.nixosModules.mango/# inputs.mangowm.nixosModules.mango/' users/{{machine}}/full.nix
        # sed -i 's/exec mango/# exec mango/' modules/{{machine}}/full.nix
        # sed -i 's/# exec start-hyprland/exec start-hyprland/' modules/{{machine}}/full.nix
        sed -i 's/mango.enable = true;/# mango.enable = true;/' users/{{machine}}/full.nix
        sed -i 's/# hyprland.enable = true;/hyprland.enable = true;/' users/{{machine}}/full.nix
        sed -i 's/..\/..\/modules/mangowm.nix/# ..\/..\/modules/mangowm.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/# ..\/..\/modules/hyprland.nix/..\/..\/modules/hyprland.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/# ..\/..\/modules/hyprpaper.nix/..\/..\/modules/hyprpaper.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/# xdg-desktop-portal-hyprland/xdg-desktop-portal-hyprland/' homemanager/{{machine}}/full.nix
        rg -i "inputs.mangowm.nixosModules.mango" users/{{machine}}/full.nix | awk '{$1=$1};1' | awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -i "xdg-desktop-portal-hyprland" homemanager/{{machine}}/full.nix | \
                awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -i "hyprland.enable = true;" homemanager/{{machine}}/full.nix | \
                awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -U -o 'imports\s*=\s*\[(\p{any}*?)\]' -r '$1' --no-line-number homemanager/{{machine}}/full.nix | \
                awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'

# install all wayland compositor 
flake-compositor $machine:
        sed -i 's/# ..\/..\/modules\/hyprland.nix/..\/..\/modules\/hyprland.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/# ..\/..\/modules\/hyprpaper.nix/..\/..\/modules\/hyprpaper.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/# ..\/..\/modules\/mangowm.nix/..\/..\/modules\/mangowm.nix/' homemanager/{{machine}}/full.nix
        sed -i 's/# ..\/..\/modules\/cosmic.nix/..\/..\/modules\/cosmic.nix/' users/{{machine}}/full.nix
        sed -i 's/# inputs.mangowm.nixosModules.mango/inputs.mangowm.nixosModules.mango/' users/{{machine}}/full.nix
        sed -i 's/# mango.enable = true;/mango.enable = true;/' users/{{machine}}/full.nix
        sed -i 's/# hyprland.enable = true;/hyprland.enable = true;/' users/{{machine}}/full.nix
        sed -i 's/# xdg-desktop-portal-hyprland/xdg-desktop-portal-hyprland/' homemanager/{{machine}}/full.nix
        rg -U -o 'imports\s*=\s*\[(\p{any}*?)\]' -r '$1' --no-line-number homemanager/{{machine}}/full.nix | \
                awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -U -o 'imports\s*=\s*\[(\p{any}*?)\]' -r '$1' --no-line-number users/{{machine}}/full.nix | \
                awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'

# display manager sddm
flake-display-sddm $machine:
        @if [[ "../../modules/ly.nix" = $(rg -i "ly.nix" users/{{machine}}/full.nix | awk '{$1=$1};1') ]]; then \
                sed -i 's/..\/..\/modules\/ly.nix/# ..\/..\/modules\/ly.nix/' users/{{machine}}/full.nix; \
        fi
        sed -i 's/# ..\/..\/modules\/sddm.nix/..\/..\/modules\/sddm.nix/' users/{{machine}}/full.nix
        rg -i "ly.nix" users/{{machine}}/full.nix | awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -i "sddm.nix" users/{{machine}}/full.nix | awk '{$1=$1};1' | awk '{print "\033[0;32m" $0 "\033[0m"}'
# display manager ly
flake-display-ly $machine:
        @if [[ "../../modules/sddm.nix" = $(rg -i "sddm.nix" users/{{machine}}/full.nix | awk '{$1=$1};1') ]]; then \
                sed -i 's/..\/..\/modules\/sddm.nix/# ..\/..\/modules\/sddm.nix/' users/{{machine}}/full.nix; \
        fi
        sed -i 's/# ..\/..\/modules\/ly.nix/..\/..\/modules\/ly.nix/' users/{{machine}}/full.nix
        rg -i "ly.nix" users/{{machine}}/full.nix | awk '{$1=$1};1' | awk '{print "\033[0;32m" $0}'
        rg -i "sddm.nix" users/{{machine}}/full.nix | awk '{$1=$1};1' | awk '{print "\033[0;32m" $0 "\033[0m"}'
# display manager tty default nixos
flake-display-tty $machine:
        sed -i 's/..\/..\/modules\/ly.nix/# ..\/..\/modules\/ly.nix/' users/{{machine}}/full.nix
        rg -i "ly.nix" users/{{machine}}/full.nix | awk '{$1=$1};1' | awk '{print "\033[0;32m" $0 "\033[0m"}'
        
# rsync fish config to host manual
to-host-fish $user:
        #!/usr/bin/env bash
        if [[ ! -d "$HOME/.config/base16-shell" ]]; then
                git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
        fi
        if command -v rsync &> /dev/null; then
                if [ "{{user}}" == "root" ]; then
                        sudo rsync -azP ../configs/.config/fish /root/.config/
                else
                        rsync -azP ../configs/.config/fish $HOME/.config/
                fi
        else
                echo "rsync command not found!"
        fi
# rsync nvim config to host manual
to-host-nvim $user:
        #!/usr/bin/env bash
        if command -v rsync &> /dev/null; then
                if [ "{{user}}" == "root" ]; then
                        sudo rsync -azP ../configs/.config/nvim /root/.config/
                else
                        rsync -azP ../configs/.config/nvim $HOME/.config/
                fi
        else
                echo "rsync command not found!"
        fi
# Partitioning disk lvm on luks "/dev/sdX|vdx|nvmX"
nixos-disk-lvm-on-luks $block:
        #!/run/current-system/sw/bin/bash
        read -p $'\033[0;31mMake sure your \033[0;33m{{block}} \033[0;31mwill destroy y/n? : ' confirm
        if [ "n" == $confirm ]; then
                exit
        fi
        printf "\033[0;31m:: Destroy drive\n\033[0m"
        # wipe disk
        wipefs -a {{block}}
        # destroy GPT & MBR data structure
        sgdisk --zap-all {{block}}
        # EFI
        sgdisk -n 1:1m:+1G -t 1:ef00 -c 1:EFI {{block}}
        # swap partition
        # sgdisk -n 2:0:+4G -t 2:8200 -c 2:SWAP {{block}}
        # LUKS
        sgdisk -n 2:0:0 -t 2:8309 -c 2:NIXLUKS {{block}}

        printf "\033[0;33m:: Create Luks\n\033[0m"
        cryptsetup luksFormat --label NIX_LUKS "{{block}}2"
        printf "\033[0;32m:: Open Luks\n\033[0m"
        cryptsetup open "{{block}}2" Luks

        pvcreate /dev/mapper/Luks
        vgcreate vg_nix /dev/mapper/Luks
        # lvcreate -L 4G -n swap $vg
        # lvcreate -L 32G -n root $vg
        lvcreate -l 100%FREE -n nix_root vg_nix
        lsblk -f
        printf "\033[0;33m:: Formatting\n\033[0m"
        mkfs.fat -F32 -n EFI_BOOT "{{block}}1"
        mkfs.ext4 -L NIX_LVM /dev/vg_nix/nix_root
        printf "\033[0;33m:: Mount\n\033[0m"
        mount /dev/vg_nix/nix_root /mnt
        mount --mkdir "{{block}}1" /mnt/boot
        lsblk -f
# Partitioning disk btrfs on luks "/dev/sdX|vdx|nvmX"
nixos-disk-btrfs-on-luks $block:
        #!/run/current-system/sw/bin/bash
        read -p $'\033[0;31mMake sure your \033[0;33m{{block}} \033[0;31mwill destroy y/n? : ' confirm
        if [ "n" == $confirm ]; then
                exit
        fi
        printf "\033[0;31m:: Destroy drive\n\033[0m"
        # wipe disk
        wipefs -a {{block}}
        # destroy GPT & MBR data structure
        sgdisk --zap-all {{block}}
        # EFI
        sgdisk -n 1:1m:+1G -t 1:ef00 -c 1:EFI {{block}}
        # swap partition
        # sgdisk -n 2:0:+4G -t 2:8200 -c 2:SWAP {{block}}
        # LUKS
        sgdisk -n 2:0:0 -t 2:8309 -c 2:NIXLUKS {{block}}

        printf "\033[0;33m:: Create Luks\n\033[0m"
        cryptsetup luksFormat --label NIX_LUKS "{{block}}2"
        printf "\033[0;32m:: Open Luks\n\033[0m"
        cryptsetup open "{{block}}2" Luks

        printf "\033[0;33m:: Formatting\n\033[0m"
        mkfs.btrfs -L NIX_BTRFS /dev/mapper/Luks
        mkfs.fat -F32 -n EFI_BOOT "{{block}}1"
        printf "\033[0;33m:: creating subvolume btrfs\n\033[0m"
        mount /dev/mapper/Luks /mnt
        cd /mnt
        btrfs subvolume create @
        btrfs subvolume create @home
        btrfs subvolume create @snapshots
        btrfs subvolume create @swap
        cd
        printf "\033[0;33m:: Unmount\n\033[0m"
        umount -R /mnt
        printf "\033[0;33m:: Mount\n\033[0m"
        mount -o compress=zstd,subvol=@ /dev/mapper/Luks /mnt
        mount --mkdir -o compress=zstd,subvol=@home /dev/mapper/Luks /mnt/home
        mount --mkdir -o compress=zstd,subvol=@snapshots /dev/mapper/Luks /mnt/.snapshots
        mount --mkdir -o noatime,subvol=@snapshots /dev/mapper/Luks /mnt/swap
        mount --mkdir "{{block}}1" /mnt/boot
        lsblk -f
        printf "\033[0;33m:: create swapfile\n\033[0m"
        # for nixos low memory use swap on the target machine in this case /mnt
        btrfs filesystem mkswapfile --size 4g --uuid clear /mnt/swap/swapfile
        # disable cow for swapfile btrfs not happy
        chattr +C /dir/file
        swapon /mnt/swap/swapfile
# Partitioning disk zfs native encryption "/dev/sdX|vdx|nvmX"
nixos-disk-zfs $block:
        #!/run/current-system/sw/bin/bash
        read -p $'\033[0;31mMake sure your \033[0;33m{{block}} \033[0;31mwill destroy y/n? : ' confirm
        if [ "n" == $confirm ]; then
                exit
        fi
        printf "\033[0;31m:: Destroy drive\n\033[0m"
        # wipe zpool
        zpool labelclear -f {{block}}
        zpool destroy rpool
        # wipe disk
        wipefs -a {{block}}
        # destroy GPT & MBR data structure
        sgdisk --zap-all {{block}}
        # EFI
        sgdisk -n 1:1m:+1G -t 1:ef00 -c 1:EFI_BOOT {{block}}
        # swap partition
        sgdisk -n 2:0:+4G -t 2:8200 -c 2:NIX_SWAP {{block}}
        # ZFS Native encryption
        sgdisk -n 3:0:0 -t 3:bf00 -c 3:NIX_ZFS_ROOT {{block}}
        # print drive
        sgdisk -p {{block}}
        printf "\033[0;33m:: Formatting\n\033[0m"
        mkfs.fat -F32 -n EFI_BOOT "{{block}}1"
        printf "\033[0;33m:: swap partition\n\033[0m"
        mkswap -L NIX_SWAP "{{block}}2"
        swapon "{{block}}2"
        # ZFS native encryption
        printf "\033[0;33m:: ZFS native encryption\n\033[0m"
        devname=$(echo "{{block}}3" | cut -d'/' -f 3)
        PARTUUID_ZFS=$(ls -al /dev/disk/by-partuuid | grep "$devname" | awk '{print $9}')
        echo "PARTUUID ZFS {{block}}3 = PARTUUID_ZFS"
        zpool create -f -o ashift=12 \
                -o autotrim=off \
                -O acltype=posixacl \
                -O xattr=sa \
                -O relatime=on \
                -O dnodesize=auto \
                -O encryption=aes-256-gcm \
                -O keyformat=passphrase \
                -O normalization=formD \
                -O compression=zstd \
                -O mountpoint=none \
                -O canmount=off \
                -O devices=off \
                -R /mnt \
        rpool /dev/disk/by-partuuid/"${PARTUUID_ZFS}"
        zfs create -o mountpoint=none rpool/ROOT
        zfs create -o mountpoint=none rpool/HOME
        zfs create -o mountpoint=/ -o canmount=noauto rpool/ROOT/zfsroot
        zfs create -o mountpoint=/home rpool/HOME/zfshome
        zfs umount -a
        zpool export rpool
        printf "\033[0;32m:: Open ZFS Encryption \n\033[0m"
        zpool import -d /dev/disk/by-partuuid/$PARTUUID_ZFS -R /mnt rpool -N
        zfs load-key -a
        zfs mount rpool/ROOT/zfsroot
        zfs mount -a
        mount --mkdir "{{block}}1" /mnt/boot
        zpool set bootfs=rpool/ROOT/zfsroot rpool
        zpool get bootfs
        zgenhostid $(hostid)
        zpool set cachefile=/etc/zfs/zfs-list.cache rpool
        mkdir -p /mnt/etc/zfs/
        cp -r /etc/zfs/zfs-list.cache /mnt/etc/zfs/
        lsblk -f
        zfs list

# Partitioning disk zfs on luks "/dev/sdX|vdx|nvmX"
nixos-disk-zfs-on-luks $block:
        #!/run/current-system/sw/bin/bash
        read -p $'\033[0;31mMake sure your \033[0;33m{{block}} \033[0;31mwill destroy y/n? : ' confirm
        if [ "n" == $confirm ]; then
                exit
        fi
        printf "\033[0;31m:: Destroy drive\n\033[0m"
        # wipe zpool
        zpool labelclear -f {{block}}
        zpool destroy rpool
        # wipe disk
        wipefs -a {{block}}
        # destroy GPT & MBR data structure
        sgdisk --zap-all {{block}}
        # EFI
        sgdisk -n 1:1m:+1G -t 1:ef00 -c 1:EFI_BOOT {{block}}
        # swap partition
        sgdisk -n 2:0:+4G -t 2:8200 -c 2:NIX_SWAP {{block}}
        # ZFS on luks
        sgdisk -n 3:0:0 -t 3:8309 -c 3:NIX_LUKS {{block}}
        printf "\033[0;33m:: Create Luks\n\033[0m"
        cryptsetup luksFormat --label NIX_LUKS "{{block}}3"
        printf "\033[0;32m:: Open Luks\n\033[0m"
        cryptsetup open "{{block}}3" Luks
        # print drive
        sgdisk -p {{block}}
        printf "\033[0;33m:: Formatting\n\033[0m"
        mkfs.fat -F32 -n EFI_BOOT "{{block}}1"
        printf "\033[0;33m:: swap partition\n\033[0m"
        mkswap -L NIX_SWAP "{{block}}2"
        swapon "{{block}}2"
        # ZFS native encryption
        printf "\033[0;33m:: ZFS native encryption\n\033[0m"
        # devname=$(echo "{{block}}3" | cut -d'/' -f 3)
        # PARTUUID_ZFS=$(ls -al /dev/disk/by-partuuid | grep "$devname" | awk '{print $9}')
        # echo "PARTUUID ZFS {{block}}3 = PARTUUID_ZFS"
        zpool create -f -o ashift=12 \
                -o autotrim=off \
                -O acltype=posixacl \
                -O xattr=sa \
                -O relatime=on \
                -O dnodesize=auto \
                -O encryption=aes-256-gcm \
                -O keyformat=passphrase \
                -O normalization=formD \
                -O compression=zstd \
                -O mountpoint=none \
                -O canmount=off \
                -O devices=off \
                -R /mnt \
        rpool /dev/mapper/luks
        zfs create -o mountpoint=none rpool/ROOT
        zfs create -o mountpoint=none rpool/HOME
        zfs create -o mountpoint=/ -o canmount=noauto rpool/ROOT/zfsroot
        zfs create -o mountpoint=/home rpool/HOME/zfshome
        zfs umount -a
        zpool export rpool
        printf "\033[0;32m:: Open ZFS Encryption \n\033[0m"
        zpool import -d /dev/disk/by-partuuid/$PARTUUID_ZFS -R /mnt rpool -N
        zfs load-key -a
        zfs mount rpool/ROOT/zfsroot
        zfs mount -a
        mount --mkdir "{{block}}1" /mnt/boot
        zpool set bootfs=rpool/ROOT/zfsroot rpool
        zpool get bootfs
        zgenhostid $(hostid)
        zpool set cachefile=/etc/zfs/zfs-list.cache rpool
        mkdir -p /mnt/etc/zfs/
        cp -r /etc/zfs/zfs-list.cache /mnt/etc/zfs/
        lsblk -f
        zfs list

# rsync dotfiles nix to host
to-host-nix:
        #!/run/current-system/sw/bin/bash
        # clone base16shell color
        if [[ ! -d "$HOME/.config/base16-shell" ]]; then
                git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell 
        fi

        if command -v rsync &> /dev/null; then
                rsync -azP ../configs/.config/alacritty $HOME/.config/ && \
                rsync -azP ../configs/.config/bspwm $HOME/.config/ && \
                rsync -azP ../configs/.config/fish $HOME/.config/ && \
                rsync -azP ../configs/.config/nvim $HOME/.config/ && \
                rsync -azP ../configs/.config/polybar $HOME/.config/ && \
                rsync -azP ../configs/.config/rofi $HOME/.config/ && \
                rsync -azP ../configs/.config/sxhkd $HOME/.config/ && \
                # rsync -azP ../configs/.config/waybar $HOME/.config/ && \
                # rsync -azP ../configs/.config/hypr $HOME/.config/ && \
                rsync -azP ../configs/.config/swappy $HOME/.config/ && \
                rsync -azP ../configs/.config/dunst $HOME/.config/ && \
                rsync -azP ../configs/.config/yazi $HOME/.config/ && \
                rsync -azP ../configs/.config/gtk-3.0 $HOME/.config/ && \
                rsync -azP ../configs/.config/gtk-4.0 $HOME/.config/ && \
                rsync -azP ../configs/.config/bottom $HOME/.config/ && \
                rsync -azP ../configs/.config/bat $HOME/.config/ && \
                # theme
                rsync -azP ../configs/.themes $HOME/ && \
                # icon
                rsync -azP ../configs/icons/Pop $HOME/.local/share/icons && \
                rsync -azP ../configs/icons/breeze_cursors $HOME/.local/share/icons && \
                rsync -azP ../configs/icons/Materia-Manjaro-2 $HOME/.local/share/icons && \
                rsync -azP ../configs/tmux/.tmux.conf $HOME/ 

                # !need sudo,doas
                # sddm look
                # sudo rsync -azP ../configs/sddm/sddm-astronaut-theme /usr/share/sddm/themes/
                # sudo rsync -azP ../configs/sddm/sddm.conf.d/ /usr/lib/sddm/sddm.conf.d/
        fi

