set quiet
bangbash := '#!/usr/bin/env bash'

gen:
        nixos-generate-config --root /mnt
install $host:
        {{bangbash}}
        nixos-install --flake .#{{host}} --verbose
build $host:
        {{bangbash}}
        sudo nixos-rebuild switch --flake .#{{host}}
flake-up:
        nix flake update

# rsync fish config manual
fish-config:
        #!/usr/bin/env bash
        if [[ ! -d "$HOME/.config/base16-shell" ]]; then
                git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
        fi
        if command -v rsync &> /dev/null; then
                rsync -azP ../configs/.config/fish $HOME/.config/
        else
                echo "rsync command not found!"
        fi

