set quiet
bangbash := '#!/usr/bin/env bash'

gen:
        nixos-generate-config --root /mnt
install $host:
        {{bangbash}}
        nixos-install --flake .#{{host}} --verbose
build $host:
        {{bangbash}}
        sudo nixos-rebuild switch --flake .#{{host}}
flake-up:
        nix flake update

# change user
flake-user $user:
        {{bangbash}}
        sed -i 's/\(user = "\)[^"]*"/\1{{user}}"/' flake.nix
# change host
flake-host $host:
        {{bangbash}}
        sed -i 's/\(host = "\)[^"]*"/\1{{host}}"/' flake.nix
# change gui
flake-full $user:
        {{bangbash}}
        sed -i 's/.\/hosts\/base.nix/.\/hosts\/full.nix/' flake.nix
        sed -i 's/.\/modules\/base.nix/.\/modules\/full.nix/' hosts/{{user}}/default.nix
# change base
flake-base $user:
        {{bangbash}}
        sed -i 's/.\/hosts\/full.nix/.\/hosts\/base.nix/' flake.nix
        sed -i 's/.\/modules\/full.nix/.\/modules\/base.nix/' hosts/{{user}}/default.nix

# rsync fish config manual
fish-config:
        #!/usr/bin/env bash
        if [[ ! -d "$HOME/.config/base16-shell" ]]; then
                git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
        fi
        if command -v rsync &> /dev/null; then
                rsync -azP ../configs/.config/fish $HOME/.config/
        else
                echo "rsync command not found!"
        fi

