#!/bin/bash

rsync -azP $HOME/project/dotfiles/.config/alacritty $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/.config/awesome $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/.config/bspwm $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/.config/fish $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/.config/nvim $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/.config/polybar $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/.config/rofi $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/.config/sxhkd $HOME/.config/
