#!/bin/bash

# clone base16shell color
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell && \

rsync -azP $HOME/project/dotfiles/configs/arch/.config/alacritty $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/awesome $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/bspwm $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/fish $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/nvim $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/polybar $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/rofi $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/sxhkd $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/waybar $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/hypr $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/swappy $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/dunst $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/yazi $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/gtk-3.0 $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/gtk-4.0 $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/bottom $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/arch/.config/bat $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/.themes $HOME/ && \
rsync -azP $HOME/project/dotfiles/tmux/.tmux.conf $HOME/

