#!/bin/bash

rsync -azP $HOME/project/dotfiles/configs/pop/.config/alacritty $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/pop/.config/awesome $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/pop/.config/bspwm $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/pop/.config/fish $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/pop/.config/nvim $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/pop/.config/polybar $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/pop/.config/rofi $HOME/.config/ && \
rsync -azP $HOME/project/dotfiles/configs/pop/.config/sxhkd $HOME/.config/
