#!/bin/bash

rsync -azP $HOME/.config/hypr $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/alacritty $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/bspwm $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/fish $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/nvim $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/polybar $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/rofi $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/sxhkd $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/hypr $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/waybar $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/swappy $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/dunst $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/yazi $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/gtk-3.0 $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/gtk-4.0 $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/bottom $HOME/project/dotfiles/configs/arch/.config/ && \
rsync -azP $HOME/.config/bat $HOME/project/dotfiles/configs/arch/.config/ && \
# theme
rsync -azP $HOME/.themes $HOME/project/dotfiles/configs/ && \
# icons
rsync -azP $HOME/.local/share/icons/Pop configs/arch/icons/ && \
rsync -azP $HOME/.local/share/icons/Materia-Manjaro-2 configs/arch/icons/ && \
rsync -azP $HOME/.local/share/icons/breeze_cursors configs/arch/icons/ && \
# sddm
rsync -azP /usr/share/sddm/themes/sddm-astronaut-theme $HOME/project/dotfiles/configs/arch/sddm/ && \
rsync -azP /usr/lib/sddm/sddm.conf.d configs/arch/sddm/ && \
# tmux
rsync -azP $HOME/.tmux.conf $HOME/project/dotfiles/tmux/.tmux.conf

# rsync -azP $HOME/.config/nix $HOME/project/dotfiles/configs/arch/nix 
