# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, vars, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Use the systemd-boot EFI boot loader.
  boot = {
  	loader = {
		systemd-boot.enable = true;
		systemd-boot.configurationLimit = 3;
		efi.canTouchEfiVariables = true;
        timeout = 2;
	};
	initrd.luks.devices.Nix-Luks-b47ff84f = {
		device = "/dev/disk/by-uuid/b47ff84f-984c-4078-81f9-5041bfb212f1";
		allowDiscards = true;
	};
    kernelParams = [
        # "quiet"
        "loglevel=3"
        "randomize_kstack_offset=on"
        "vsyscall=none"
    ];
  };

  fileSystems."/" = {
    options = [
      "noatime"
      "nodiratime"
      "discard"
    ];
  };

  fileSystems."/" =
    { device = "/dev/mapper/vg_nix-lv_root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8444-33B6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [{
  	device = "/var/lib/swapfile";
	size = 4*1024;
  }];

  nixpkgs.hostPlatform = lib.mkDefault "${vars.system}";
}

