# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  outputs,
  config,
  info,
  pkgs,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # hardware.opengl.enable = true;
  hardware = {
        graphics.enable = true;
        enableRedistributableFirmware = true;
  };

  # Use the systemd-boot EFI boot loader.
  boot = {
    extraModulePackages = [];
    kernelModules = [];
    loader = {
        grub.enable = false;
        generic-extlinux-compatible.enable = true;
    };
    initrd = {
      luks.devices.NIX_LUKS = {
        device = "/dev/disk/by-label/NIX_LUKS";
        allowDiscards = true;
      };
      availableKernelModules = [
        "xhci_pci"
        "usbhid"
        "usb_storage"
      ];
      kernelModules = [];
      network = {
        enable = true;
        ssh = {
          enable = true;
          port = 22;
          authorizedKeys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEiAmmDigF8/qT06o2mQ1HVbJ9QCyxp/v7uRZxlBYMpb brandon.earendel"];
          # need to execute so ssh can start in initrd -->
          # mkdir -p /etc/secrets/initrd
          # ssh-keygen -t ed25519 -N "" -f /etc/secrets/initrd/ssh_host_ed25519_key
          hostKeys = ["/etc/secrets/initrd/ssh_host_ed25519_key"];
          # shell = "/usr/bin/systemd-tty-ask-password-agent";
        };
      };
      systemd.users.root.shell = "/usr/bin/systemd-tty-ask-password-agent";
    };
    kernelParams = [
      # "quiet"
      "loglevel=3"
      "ip=dhcp"
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIX_BTRFS";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/NIX_BTRFS";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=@home" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-label/NIX_BTRFS";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=@snapshots" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-label/NIX_BTRFS";
      fsType = "btrfs";
      options = [ "noatime" "subvol=@swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/NIX_BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
