# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, system, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Use the systemd-boot EFI boot loader.
  boot = {
  	loader = {
		# systemd-boot.enable = true;
		# systemd-boot.configurationLimit = 5;
        limine.enable = true;
        limine.maxGenerations = 5;
		efi.canTouchEfiVariables = true;
		# efi.efiSysMountPoint = "/boot/EFI";
        timeout = 2;
	};
	initrd = {
	    # luks.devices.Nix-Luks-0fd9cedc = {
	    # 	device = "/dev/disk/by-uuid/0fd9cedc-8210-47ea-a5fd-45a0b708eeb8";
	    # 	allowDiscards = true;
	    # };
        luks.devices.NIX_LUKS = {
	    	device = "/dev/disk/by-label/NIX_LUKS";
	    	allowDiscards = true;
	    };
        availableKernelModules = [
                "ahci"
                "xhci_pci"
                "virtio_pci"
                "sr_mod"
                "virtio_blk"
                # "r8169"
        ];
        kernelModules = [ "dm-snapshot" ];
        network = {
                enable = true;
                ssh = {
                        enable = true;
                        port = 22;
                        authorizedKeys = [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFCMCsfI7ZZjtHp63JxrFWMfsQHwDUVAb7TbsO3ChOzc walter.vm" ];
                        hostKeys = [ "/etc/secrets/initrd/ssh_host_ed25519_key" ];
                        shell = "/usr/bin/systemd-tty-ask-password-agent";
                };
        };
        systemd.users.root.shell = "/usr/bin/systemd-tty-ask-password-agent";
    };
    kernelParams = [
        # "quiet"
        "loglevel=3"
        "randomize_kstack_offset=on"
        "vsyscall=none"
        "ip=dhcp"
    ];
  };

  fileSystems."/" =
    { device = "/dev/mapper/vg_nix-nix_root";
      fsType = "ext4";
    };

  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/A3C6-0817";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/EFI_BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [{
  	device = "/var/lib/swapfile";
	size = 4*1024;
  }];

  nixpkgs.hostPlatform = lib.mkDefault "${system}";
}

