#!/usr/bin/bash

# pacman download slow
sed -i 's/^.*HookDir.*/HookDir     = \/etc\/pacman.d\/hooks\//' /etc/pacman.conf
sed -i 's/Parall.*/ParallelDownloads = 20/' /etc/pacman.conf
sed -i 's/#Color/Color\nILoveCandy/' /etc/pacman.conf
sed -i 's/DownloadUser = alpm/#DownloadUser = alpm/' /etc/pacman.conf
sed -i 's/^.*multilib]/[multilib]/' /etc/pacman.conf
sed -i '95s/^.*Include =.*/Include = \/etc\/pacman.d\/mirrorlist/g' /etc/pacman.conf

printf "\033[0;31m"
grep -nE '^.*HookDir.*' /etc/pacman.conf
grep -nE 'Parall.*' /etc/pacman.conf
grep -nE 'Color' /etc/pacman.conf
grep -nE 'ILoveCandy' /etc/pacman.conf
grep -nE 'DownloadUser = alpm.*' /etc/pacman.conf
grep -nE '^.*multilib]' /etc/pacman.conf
grep -nE '^.*Include =.*' /etc/pacman.conf | grep 95
printf "\033[0m"

BLOCK="/dev/vda"
luksname="luksbtrfs" 
bootloader="/boot/EFI/limine/limine.conf"
initconf="/etc/mkinitcpio.conf"
hostname="kiwi.vm"

# Partitioning
printf "\033[0;31m:: Partitioning\n\033[0m"

# wipe disk
wipefs -a $BLOCK

# destroy GPT & MBR data structure
sgdisk --zap-all $BLOCK

# EFI
sgdisk -n 1:2m:+1G -t 1:ef00 -c 1:EFI $BLOCK

# swap partition
# sgdisk -n 2::+2G -t 2:8200 -c 2:SWAP $BLOCK

# Luks partition
sgdisk -n 2:0:0 -t 2:8309 -c 2:LUKS $BLOCK

# print drive
printf "\033[0;34m:: Result\n\033[0m"
sgdisk -p $BLOCK

# BTRFS on LUKS
printf "\033[0;33m:: BTRFS on LUKS\n\033[0m"

cryptsetup luksFormat "${BLOCK}2"
printf "\033[0;33m:: Open Luks\n\033[0m"
cryptsetup open "${BLOCK}2" $luksname

mkfs.fat -F32 -n EFI_BOOT "${BLOCK}1"
mkfs.btrfs -L LUKSBTRFS "/dev/mapper/${luksname}"
mount "/dev/mapper/${luksname}" /mnt
cd /mnt
btrfs subvolume create @
btrfs subvolume create @home
btrfs subvolume create @snapshots
cd
umount -R /mnt
mount -o compress=zstd,subvol=@ "/dev/mapper/${luksname}" /mnt
mount --mkdir -o compress=zstd,subvol=@home "/dev/mapper/${luksname}" /mnt/home
mount --mkdir -o compress=zstd,subvol=@snapshots "/dev/mapper/${luksname}" /mnt/.snapshots
mount --mkdir "${BLOCK}1" /mnt/boot
LUKSNAME=$(lsblk -f | grep crypto_LUKS | awk '{print $4}' | awk -F '-' '{print $1}')
LUKSUUID=$(lsblk -f | grep crypto_LUKS | awk '{print $4}')
lsblk -f

# pacstrap
printf "\033[0;34m:: Pacstrap\n\033[0m"
pacstrap -K /mnt base base-devel linux linux-headers linux-firmware efibootmgr dosfstools networkmanager \
        fish git ripgrep fd bottom rsync neovim btrfs-progs e2fsprogs openssh git-delta

# generate fstab
printf "\033[0;34m:: Generate fstab\n\033[0m"
genfstab -U /mnt >> /mnt/etc/fstab

printf "#!/usr/bin/bash

# configure chroot system
ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
hwclock --systohc --verbose

sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

echo 'LANG=en_US.UTF-8' > /etc/locale.conf
echo 'KEYMAP=us' > /etc/vconsole.conf

echo \"$hostname\" > /etc/hostname

systemctl enable NetworkManager
systemctl enable sshd

# config for btrfs on luks
sed -i 's/^HOOKS=(.*/HOOKS=(base systemd autodetect microcode modconf kms keyboard sd-vconsole block sd-encrypt filesystems fsck)/' $initconf

# generate initramfs
mkinitcpio -P

# bootloader
printf \"\\\033[0;32m:: Bootlader\\\n\\\033[0m\"
pacman -S --needed --noconfirm limine efibootmgr

mkdir -p /boot/EFI/limine
cp /usr/share/limine/BOOTX64.EFI /boot/EFI/limine/

printf \"timeout: 3
# wallpaper: boot():/EFI/limine/limine.png
# wallpaper_style: centered
backdrop: centered
remember_last_entry: yes

/+ Arch Linux
        // Linux
                protocol: linux
                path: boot():/vmlinuz-linux
                cmdline: rd.luks.name=%%s=luks-%%s root=/dev/mapper/luks-%%s rw rootflags=subvol=@ rootfstype=btrfs loglevel=3 
                module_path: boot():/initramfs-linux.img
# / Grub Boot Loader
#         protocol: efi
#         path: boot():/EFI/grub/grubx64.efi
\" \"${LUKSUUID}\" \"${LUKSNAME}\" \"${LUKSNAME}\" > $bootloader

mkdir -p /etc/pacman.d/hooks
printf \"[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = limine

[Action]
Description = Deploying Limine after upgrade...
When = PostTransaction
Exec = /usr/bin/cp /usr/share/limine/BOOTX64.EFI /boot/EFI/limine/\\n\" > /etc/pacman.d/hooks/99-limine.hook

printf \"\\\033[0;32m:: efibootmgr List\\\n\\\033[0m\"
efibootmgr --create --disk $BLOCK --part 1 --label 'Arch Linux Limine Boot Loader' --loader '\\\EFI\\\limine\\\BOOTX64.EFI' --unicode 
efibootmgr

printf \"\\\033[0;32m:: User\\\n\\\033[0m\"
sed -i 's/^.*sudo ALL.*/%%sudo ALL=(ALL:ALL) ALL/' /etc/sudoers

groupadd rigel
groupadd sudo
useradd -g rigel -m rigel -s /usr/bin/fish
usermod -aG sudo rigel
printf \"\\\033[0;32m:: passwd root\\\n\\\033[0m\"
passwd
printf \"\\\033[0;32m:: passwd rigel\\\n\\\033[0m\"
passwd rigel

sed -i 's/^.*HookDir.*/HookDir     = \\\/etc\\\/pacman.d\\\/hooks\\\//' /etc/pacman.conf
sed -i 's/Parall.*/ParallelDownloads = 12/' /etc/pacman.conf
sed -i 's/#Color/Color\\\nILoveCandy/' /etc/pacman.conf
sed -i 's/DownloadUser = alpm/#DownloadUser = alpm/' /etc/pacman.conf
sed -i 's/^.*multilib]/[multilib]/' /etc/pacman.conf
sed -i '95s/^.*Include =.*/Include = \\\/etc\\\/pacman.d\\\/mirrorlist/g' /etc/pacman.conf

grep -nE '^.*HookDir.*' /etc/pacman.conf
grep -nE 'Parall.*' /etc/pacman.conf
grep -nE 'Color' /etc/pacman.conf
grep -nE 'ILoveCandy' /etc/pacman.conf
grep -nE 'DownloadUser = alpm.*' /etc/pacman.conf
grep -nE '^.*multilib]' /etc/pacman.conf
grep -nE '^.*Include =.*' /etc/pacman.conf | grep 95
" > /mnt/root/configure_system

chmod +x /mnt/root/configure_system

# chroot
printf "\033[0;32m:: Chroot\n\033[0m"
arch-chroot /mnt /root/configure_system

# cleanup
printf "\033[0;32m:: Cleanup\n\033[0m"
rm -rf /mnt/root/configure_system
