#!/usr/bin/env bash
for i in {1..5}
do
    text=$(curl -s "https://wttr.in/$1?format=1")
    if [[ $? == 0 ]]
    then
        text=$(echo "$text" | sed -E "s/\s+/ /g")
        tooltip=$(curl -s "https://wttr.in/$1?format=3")
        temp=$(echo "$text" | grep -oE '[0-9]+')
        if (( temp >= 0 && temp < 23));
        then
            tooltip="<span color='#3C3836'>$(echo "$tooltip" | sed -E "s/\s+/ /g")</span>"
            echo "{\"text\":\"<span color='#3C3836'>+$temp°C</span>\", \"tooltip\":\"$tooltip\"}"
            exit
        elif (( temp >= 23 && temp < 25));
        then
            tooltip="<span color='#ebdbb2'>$(echo "$tooltip" | sed -E "s/\s+/ /g")</span>"
            echo "{\"text\":\"<span color='#ebdbb2'>+$temp°C</span>\", \"tooltip\":\"$tooltip\"}"
            exit
        elif (( temp >= 25 && temp < 29));
        then
            tooltip="<span color='#fabd2f'>$(echo "$tooltip" | sed -E "s/\s+/ /g")</span>"
            echo "{\"text\":\"<span color='#fabd2f'>+$temp°C</span>\", \"tooltip\":\"$tooltip\"}"
            exit
        elif (( temp >= 29 ));
        then
            tooltip="<span color='#fb4934'>$(echo "$tooltip" | sed -E "s/\s+/ /g")</span>"
            echo "{\"text\":\"<span color='#fb4934'>+$temp°C</span>\", \"tooltip\":\"$tooltip\"}"
            exit
        fi
    fi
    sleep 2
done
echo "{\"text\":\"error\", \"tooltip\":\"error\"}"
