# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Use the systemd-boot EFI boot loader.
  boot = {
  	loader = {
		# systemd-boot.enable = true;
		# systemd-boot.configurationLimit = 3;
        limine.enable = true;
        limine.maxGenerations = 5;
		efi.canTouchEfiVariables = true;
		# efi.efiSysMountPoint = "/boot/EFI";
        timeout = 2;
	};
	# initrd.luks.devices.Nix-Luks-e1aaf288 = {
	# 	device = "/dev/disk/by-uuid/e1aaf288-17ca-49e9-a91b-afaade4506c9";
	# 	allowDiscards = true;
	# };
    kernelParams = [
        "quiet"
        "loglevel=3"
        "randomize_kstack_offset=on"
        "vsyscall=none"
    ];
  };

  fileSystems."/" =
    { device = "/dev/mapper/vg_nix-nix_root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/EFI_BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [{
  	device = "/var/lib/swapfile";
	size = 4*1024;
  }];

  # microcode
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.hostPlatform = lib.mkDefault "${system}";
}

