#!/bin/bash

echo "disable root Bash history"
sleep 2
echo "HISTFILESIZE=0" >> ~/.bashrc
history -c; history -w
source ~/.bashrc

echo "disable pi sudo nopassword feature"
rm /etc/sudoers.d/010_*

echo -e "disable Bluetooth and Wi-Fi"
sleep 1
echo "dtoverlay=disable-bt" >> /boot/config.txt
sleep 1
echo "dtoverlay=disable-wifi" >> /boot/config.txt

echo "configure sysctl (if network is IPv4-only)"
sleep 2
cp /etc/sysctl.conf /etc/sysctl.conf.backup
cat << "EOF" >> /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF
sysctl -p


