# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  outputs,
  config,
  info,
  pkgs,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  # opengl vm
  # setting on vm manager GUI on host machine
  # <graphics type="spice">
  #    <listen type="none"/>
  #    <image compression="off"/>
  #    <gl enable="yes" rendernode="/dev/dri/by-path/pci-0000:00:02.0-render"/> # this just pick either betweeb 2 gpu
  # </graphics>
  # <video>
  #       <model type="virtio" heads="1" primary="yes">
  #         <acceleration accel3d="yes"/>
  #       </model>
  #       <alias name="video0"/>
  #       <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0"/>
  # </video>

  # hardware.opengl.enable = true;
  hardware.graphics.enable = true;

  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  # Use the systemd-boot EFI boot loader.
  boot = {
    loader = {
      # systemd-boot.enable = true;
      # systemd-boot.configurationLimit = 5;
      limine.enable = true;
      limine.maxGenerations = 5;
      efi.canTouchEfiVariables = true;
      # efi.efiSysMountPoint = "/boot/EFI";
      timeout = 2;
    };
    initrd = {
      # luks.devices.Nix-Luks-0fd9cedc = {
      # 	device = "/dev/disk/by-uuid/0fd9cedc-8210-47ea-a5fd-45a0b708eeb8";
      # 	allowDiscards = true;
      # };
      luks.devices.NIX_LUKS = {
        device = "/dev/disk/by-label/NIX_LUKS";
        allowDiscards = true;
      };
      availableKernelModules = [
        "ahci"
        "xhci_pci"
        "virtio_pci"
        "sr_mod"
        "virtio_blk"
        # "r8169"
      ];
      kernelModules = ["dm-snapshot"];
      network = {
        enable = true;
        ssh = {
          enable = true;
          port = 22;
          authorizedKeys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFCMCsfI7ZZjtHp63JxrFWMfsQHwDUVAb7TbsO3ChOzc walter.vm"];
          # need to execute so ssh can start in initrd -->
          # mkdir -p /etc/secrets/initrd
          # ssh-keygen -t ed25519 -N "" -f /etc/secrets/initrd/ssh_host_ed25519_key
          hostKeys = ["/etc/secrets/initrd/ssh_host_ed25519_key"];
          # shell = "/usr/bin/systemd-tty-ask-password-agent";
        };
      };
      systemd.users.root.shell = "/usr/bin/systemd-tty-ask-password-agent";
    };
    kernelParams = [
      # "quiet"
      "loglevel=3"
      "randomize_kstack_offset=on"
      "vsyscall=none"
      "ip=dhcp"
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIX_BTRFS";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/NIX_BTRFS";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-label/NIX_BTRFS";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" " compress=zstd" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-label/NIX_BTRFS";
      fsType = "btrfs";
      options = [ "subvol=@swap" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/EFI_BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 4 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}

