#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -C ~/.config/sxhkd/sxhkdrc &

#nitrogen wallpaper restore
nitrogen --restore &
#polybar
#polybar -c ~/.config/polybar/config main &
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -c ~/.config/polybar/config main &

bspc monitor -d Web Code 4 5

bspc config border_width         0
bspc config window_gap          2
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefoxdeveloperedition desktop='^2' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a polybar border=off manage=off

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

hdmi=$(xrandr -q | grep 'HDMI-1' | awk '/ connected /{print $2}')
if [ $hdmi = 'connected' ]
then
        # echo $hdmi
        $HOME/utility/xrandr-off-eDP-1 &
        $HOME/project/dotfiles/scripts/xrandr-HDMI-1-rate-60 &
        nitrogen --restore &
fi

