#!/run/current-system/sw/bin/env bash
for i in {1..5}
do
    text=$(curl -s "https://wttr.in/$1?format=1")
    if [[ $? == 0 ]]
    then
        text=$(echo "$text" | sed -E "s/\s+/ /g")
        tooltip=$(curl -s "https://wttr.in/$1?format=4")
        temp=$(echo "$text" | grep -oE '[0-9]+')
        if (( temp >= 0 && temp <= 23));
        then
            tooltip="<span color='#75695f'>$(echo "$tooltip" | sed -E "s/\s+/ /g")</span>"
            echo "{\"text\":\"<span color='#a89984'>$text</span>\", \"tooltip\":\"$tooltip\"}"
            exit
        elif (( temp >= 23 && n <= 25));
        then
            tooltip=$(echo "$tooltip" | sed -E "s/\s+/ /g")
            echo "{\"text\":\"<span color='#ebdbb2'>$text</span>\", \"tooltip\":\"$tooltip\"}"
            exit
        elif (( temp >= 25 && n <= 29));
        then
            tooltip=$(echo "$tooltip" | sed -E "s/\s+/ /g")
            echo "{\"text\":\"<span color='#fe8019'>$text</span>\", \"tooltip\":\"$tooltip\"}"
            exit
        elif (( temp >= 29 ));
        then
            tooltip=$(echo "$tooltip" | sed -E "s/\s+/ /g")
            echo "{\"text\":\"<span color='#cc241d'>$text</span>\", \"tooltip\":\"$tooltip\"}"
            exit
        fi
    fi
    sleep 2
done
echo "{\"text\":\"error\", \"tooltip\":\"error\"}"
