#!/bin/bash

rsync -azP $HOME/.config/hypr $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/alacritty $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/awesome $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/bspwm $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/fish $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/nvim $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/polybar $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/rofi $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/sxhkd $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/hypr $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/waybar $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.config/swappy $HOME/project/dotfiles/.config/arch/ && \
rsync -azP $HOME/.tmux.conf $HOME/project/dotfiles/.tmux.conf

# rsync -azP $HOME/.config/nix $HOME/project/dotfiles/.config/arch/nix 
