#!/bin/bash

rsync -azP $HOME/.config/alacritty $HOME/project/dotfiles/.config/alacritty && \
rsync -azP $HOME/.config/awesome $HOME/project/dotfiles/.config/awesome && \
rsync -azP $HOME/.config/bspwm $HOME/project/dotfiles/.config/bspwm && \
rsync -azP $HOME/.config/fish $HOME/project/dotfiles/.config/fish && \
rsync -azP $HOME/.config/nvim $HOME/project/dotfiles/.config/nvim && \
rsync -azP $HOME/.config/polybar $HOME/project/dotfiles/.config/polybar && \
rsync -azP $HOME/.config/rofi $HOME/project/dotfiles/.config/rofi && \
rsync -azP $HOME/.config/sxhkd $HOME/project/dotfiles/.config/sxhkd 
