# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, system, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Intel graphic on cpu
  hardware.graphics.extraPackages = with pkgs; [
    intel-compute-runtime-legacy1
    intel-vaapi-driver
    libva-vdpau-driver
  ];

  # nvidia 1660 super
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ 
        "modesetting" # example for Intel iGPU; use "amdgpu" here instead if your iGPU is AMD
        "nvidia" 
  ];
  hardware.nvidia = {
          # Modesetting is required.
          modesetting.enable = true;

          # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
          # Enable this if you have graphical corruption issues or application crashes after waking 
          # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead 
          # of just the bare essentials.
          powerManagement.enable = false;

          # Fine-grained power management. Turns off GPU when not in use.
          # Experimental and only works on modern Nvidia GPUs (Turing or newer).
          powerManagement.finegrained = false;

          # Use the NVidia open source kernel module (not to be confused with the
          # independent third-party "nouveau" open source driver).
          # Support is limited to the Turing and later architectures. Full list of 
          # supported GPUs is at: 
          # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus 
          # Only available from driver 515.43.04+
          open = true;

          # Enable the Nvidia settings menu,
          # accessible via `nvidia-settings`.
          nvidiaSettings = true;

          # Optionally, you may need to select the appropriate driver version for your specific GPU.
          package = config.boot.kernelPackages.nvidiaPackages.stable;

          # PRIME offload mode
          prime = {
                  offload = {
                          enable = true;
                          enableOffloadCmd = true;
                  };
                  # sudo lshw -c display
                  # or
                  # nix shell nixpkgs#pciutils -c lspci -D -d ::03xx
                  # Make sure to use the correct Bus ID values for your system!
                  intelBusId = "PCI:0:2:0";
                  nvidiaBusId = "PCI:1:0:0";
                  # amdgpuBusId = "PCI:54:0:0"; For AMD GPU
          };
  };

  # microcode
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;


  # Use the systemd-boot EFI boot loader.
  boot = {
  	loader = {
		# systemd-boot.enable = true;
		# systemd-boot.configurationLimit = 3;
        limine.enable = true;
        limine.maxGenerations = 5;
		efi.canTouchEfiVariables = true;
		# efi.efiSysMountPoint = "/boot/EFI";
        timeout = 2;
	};
	# initrd.luks.devices.Nix-Luks-e1aaf288 = {
	# 	device = "/dev/disk/by-uuid/e1aaf288-17ca-49e9-a91b-afaade4506c9";
	# 	allowDiscards = true;
	# };
    kernelParams = [
        # "quiet"
        "loglevel=3"
        "randomize_kstack_offset=on"
        "vsyscall=none"
    ];
  };

  fileSystems."/" =
    { device = "/dev/mapper/vg_nix-nix_root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/EFI_BOOT";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [{
  	device = "/var/lib/swapfile";
	size = 4*1024;
  }];

  nixpkgs.hostPlatform = lib.mkDefault "${system}";
}

